[versions]
agp = "8.3.2"
core-ktx = "1.13.1"
datastore-preferences = "1.1.1"
hilt-navigation-compose = "1.2.0"
integrity = "1.3.0"
kotlin = "1.9.22"
coroutines = "1.8.0"
ksp = "1.9.22-1.0.17"
gms = "4.4.1"
dagger = "2.51.1"
lifecycle-runtime-ktx = "2.7.0"
navigation-compose = "2.7.7"
coil = "2.6.0"
compose-bom = "2024.05.00"
firebase-bom = "33.0.0"
app-update = "2.1.0"
crashlytics = "3.0.0"
#youtube = "12.1.0"
gson = "2.10.1"
decompose = "3.0.0"
decompose-old = "2.2.3"
mvikotlin = "4.0.0"
mvikotlin-old = "3.3.0"

[libraries]
# Compose
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-material = { module = "androidx.compose.material3:material3" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-runtime-ktx" }
# Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-auth = { module = "com.google.firebase:firebase-auth-ktx" }
firebase-storage = { module = "com.google.firebase:firebase-storage-ktx" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore-ktx" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
# Google
app-update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "app-update" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
integrity = { module = "com.google.android.play:integrity", version.ref = "integrity" }
#youtube-core = { module = "com.pierfrancescosoffritti.androidyoutubeplayer:core", version.ref = "youtube" }
# Core
androidx-core = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore-preferences" }
# DI
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
# Navigation
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
# Coroutines
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
# Image
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
# Decompose
decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-jetpack = { module = "com.arkivanov.decompose:extensions-compose-jetpack", version.ref = "decompose-old" }
# MVI
mvikotlin-rx = { module = "com.arkivanov.mvikotlin:rx", version.ref = "mvikotlin-old" }
mvikotlin = { module = "com.arkivanov.mvikotlin:mvikotlin", version.ref = "mvikotlin" }
mvikotlin-main = { module = "com.arkivanov.mvikotlin:mvikotlin-main", version.ref = "mvikotlin" }
mvikotlin-logging = { module = "com.arkivanov.mvikotlin:mvikotlin-logging", version.ref = "mvikotlin" }
mvikotlin-extensions-coroutines = { module = "com.arkivanov.mvikotlin:mvikotlin-extensions-coroutines", version.ref = "mvikotlin" }
# Test
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[plugins]
application = { id = "com.android.application", version.ref = "agp" }
library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-services = { id = "com.google.gms.google-services", version.ref = "gms" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }

[bundles]
di = ["hilt-android", "hilt-navigation-compose"]
core = ["androidx-core", "lifecycle-runtime-ktx"]
compose = ["androidx-foundation", "androidx-runtime", "androidx-material",
    "androidx-material-icons-extended", "androidx-ui", "androidx-ui-graphics",
    "androidx-ui-tooling", "androidx-ui-tooling-preview", "androidx-lifecycle-viewmodel-compose"]
firebase = ["firebase-auth", "firebase-storage", "firebase-firestore", "firebase-crashlytics", "firebase-analytics"]
decompose = ["decompose", "decompose-jetpack"]
mvikotlin = ["mvikotlin", "mvikotlin-rx", "mvikotlin-main", "mvikotlin-logging", "mvikotlin-extensions-coroutines"]