[versions]
agp = "8.1.1"
core-ktx = "1.12.0"
hilt-android = "2.48"
kotlin = "1.8.10"
ksp = "1.8.10-1.0.9"
gms = "4.4.0"
dagger = "2.48"

[libraries]
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt-android" }


[plugins]
application = { id = "com.android.application", version.ref = "agp" }
library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-services = { id = "com.google.gms.google-services", version.ref = "gms" }


[bundles]

