[versions]
activity-compose = "1.8.0"
agp = "8.1.2"
androidx-junit = "1.1.5"
compose = "1.0.0-beta01"
core = "1.9.54"
core-ktx = "1.12.0"
datastore-preferences = "1.0.0"
espresso-core = "3.5.1"
hilt-android = "2.48"
hilt-navigation-compose = "1.0.0"
junit = "4.13.2"
kotlin = "1.8.10"
ksp = "1.8.10-1.0.9"
gms = "4.4.0"
dagger = "2.48"
lifecycle-runtime-ktx = "2.6.2"
navigation-compose = "2.7.4"
coil = "2.4.0"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
compose = { module = "com.github.bumptech.glide:compose", version.ref = "compose" }
core = { module = "io.github.raamcosta.compose-destinations:core", version.ref = "core" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore-preferences" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt-android" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
junit = { module = "junit:junit", version.ref = "junit" }
ksp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "core" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

[plugins]
application = { id = "com.android.application", version.ref = "agp" }
library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-services = { id = "com.google.gms.google-services", version.ref = "gms" }

[bundles]

